### PR TITLE
mark msgpack-charset as a Charset

### PR DESCRIPTION
**Pull request by MichaelBlume**
remove all reflection

### CODE REVIEW

**Comment by edma2** [comment]
Thanks for the patch. Do you mind expanding the commit message with motivation and what this solves exactly?

**Comment by MichaelBlume** [comment]
I thought "remove all reflection" was pretty clear, but I will try to think
of something more verbose to say :)

**Comment by edma2** [comment]
I think you provided a sufficient reason (less reflection is better, obviously). I'm mostly curious about what prompted the change. Did this fix a linter warning, or was it just something you found by reading the code?

**Comment by MichaelBlume** [comment]
Hey, sorry about that, I saw this as I was waking up, made a snarky reply, and then forgot about it. Not cool. Anyhow, I think I ran 'lein check' on my own project, and saw the reflection warnings coming from clojure-msgpack and saw that there were some java-interop calls that were compiling into reflective calls because they couldn't infer the type of msgpack-charset.

**Comment by edma2** [comment]
I see, thanks :)

**Pull request merged**
